version: "2"

run:
  timeout: 5m
  concurrency: 4

linters:
  enable:
    - gocyclo
    - staticcheck
    - errcheck
    - govet
    - unused
    - bodyclose
    - noctx
    - asasalint
    #- revive
    - gosec
    - nilerr
  settings:
    gocyclo:
      min-complexity: 20
    revive:
      confidence: 0.8